[project]
name = "project-8-virtualmachine"
version = "0.1.0"
description = "verifies the functionality of the virtual machine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradescope-utils>=0.5.0",
]
